<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="psm" nsURI="http://blackbelt.hu/judo/meta/psm" nsPrefix="psm">
  <eSubpackages name="namespace" nsURI="http://blackbelt.hu/judo/meta/psm/namespace"
      nsPrefix="namespace">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//namespace/NamespaceElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
          eType="#//namespace/Package" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//namespace/Namespace"/>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//namespace/Namespace"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamespaceElement" abstract="true"
        eSuperTypes="#//namespace/NamedElement"/>
  </eSubpackages>
  <eSubpackages name="type" nsURI="http://blackbelt.hu/judo/meta/psm/type" nsPrefix="type">
    <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true" eSuperTypes="#//type/DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="CustomType" eSuperTypes="#//type/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//type/Primitive">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="regExp" eType="#//type/RegExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumericType" eSuperTypes="#//type/Primitive">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//type/Primitive"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationType" eSuperTypes="#//type/Primitive">
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//type/EnumerationMember" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationMember" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//namespace/NamespaceElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//type/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="XMLType" eSuperTypes="#//type/Primitive">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmlNamespace" eType="#//type/XmlNamespace"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmlElement" eType="#//type/XmlElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cardinality">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="RegExp" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EClass" name="PasswordType" eSuperTypes="#//type/Primitive"/>
    <eClassifiers xsi:type="ecore:EDataType" name="XmlNamespace" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="XmlElement" instanceClassName="java.lang.String"/>
  </eSubpackages>
  <eSubpackages name="data" nsURI="http://blackbelt.hu/judo/meta/psm/data" nsPrefix="data">
    <eClassifiers xsi:type="ecore:EClass" name="EntityType" eSuperTypes="#//type/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="superEntityTypes" upperBound="-1"
          eType="#//data/EntityType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//data/Attribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
          eType="#//data/Relation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationCountConstraints"
          upperBound="-1" eType="#//data/RelationCountConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataProperties" upperBound="-1"
          eType="#//derived/DataProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="navigationProperties"
          upperBound="-1" eType="#//derived/NavigationProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//service/BoundOperation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" eSuperTypes="#//data/ReferenceTypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascadeDelete" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//data/PrimitiveTypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Endpoint" eSuperTypes="#//data/Relation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="partner" eType="#//data/Endpoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationCountConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" lowerBound="2"
          upperBound="-1" eType="#//data/Relation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" lowerBound="1"
          eType="#//type/Cardinality" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceTypedElement" abstract="true"
        eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//data/EntityType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" lowerBound="1"
          eType="#//type/Cardinality" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypedElement" abstract="true"
        eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
          eType="#//type/Primitive"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Containment" eSuperTypes="#//data/Relation"/>
  </eSubpackages>
  <eSubpackages name="behavior" nsURI="http://blackbelt.hu/judo/meta/psm/behavior"
      nsPrefix="behavior"/>
  <eSubpackages name="constraint" nsURI="http://blackbelt.hu/judo/meta/psm/constraint"
      nsPrefix="constraint">
    <eClassifiers xsi:type="ecore:EClass" name="InvariantConstraint" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//LogicalExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrained" lowerBound="1"
          eType="#//data/EntityType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="script" nsURI="http://blackbelt.hu/judo/meta/psm/script" nsPrefix="script">
    <eClassifiers xsi:type="ecore:EDataType" name="Script" instanceClassName="java.lang.String"/>
  </eSubpackages>
  <eSubpackages name="derived" nsURI="http://blackbelt.hu/judo/meta/psm/derived" nsPrefix="derived">
    <eClassifiers xsi:type="ecore:EClass" name="DataProperty" eSuperTypes="#//derived/PrimitiveAccessor"/>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationProperty" eSuperTypes="#//derived/ReferenceAccessor"/>
    <eClassifiers xsi:type="ecore:EClass" name="StaticNavigation" eSuperTypes="#//derived/ReferenceAccessor #//namespace/NamespaceElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveAccessor" abstract="true"
        eSuperTypes="#//data/PrimitiveTypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="getterExpression" lowerBound="1"
          eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//DataExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="setterExpression" eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//AttributeSelector"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaticData" eSuperTypes="#//derived/PrimitiveAccessor #//namespace/NamespaceElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceAccessor" abstract="true"
        eSuperTypes="#//data/ReferenceTypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="getterExpression" lowerBound="1"
          eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//ReferenceExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="setterExpression" eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//ReferenceSelector"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rangeExpression" eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//ReferenceExpression"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="service" nsURI="http://blackbelt.hu/judo/meta/psm/service" nsPrefix="service">
    <eClassifiers xsi:type="ecore:EClass" name="TransferObjectType" abstract="true"
        eSuperTypes="#//type/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="representation" eType="#//service/TransferAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
          eType="#//service/TransferRelation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//service/TransferAttribute" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransferRelation" abstract="true"
        eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" lowerBound="1"
          eType="#//type/Cardinality" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//ReferenceExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransferObjectReference" eSuperTypes="#//service/TransferRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" lowerBound="1"
          eType="#//service/MappedTransferObjectType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransferObjectContainment" eSuperTypes="#//service/TransferRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containment" lowerBound="1"
          eType="#//service/TransferObjectType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransferAttribute" eSuperTypes="#//namespace/NamedElement #//data/PrimitiveTypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="ecore:EClass http://blackbelt.hu/judo/meta/expression#//DataExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MappedTransferObjectType" eSuperTypes="#//service/TransferObjectType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entityType" lowerBound="1"
          eType="#//data/EntityType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferRelationBindings"
          upperBound="-1" eType="#//service/TransferRelationBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferAttributeBindings"
          upperBound="-1" eType="#//service/TransferAttributeBinding" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransferAttributeBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypedElement"
          lowerBound="1" eType="#//data/PrimitiveTypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferAttribute" lowerBound="1"
          eType="#//service/TransferAttribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransferRelationBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTypedElement"
          lowerBound="1" eType="#//data/ReferenceTypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferRelation" lowerBound="1"
          eType="#//service/TransferRelation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="#//script/Script"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//service/TransferObjectType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faults" upperBound="-1"
          eType="#//service/TransferObjectType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undefined" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnmappedTransferObjectType" eSuperTypes="#//service/TransferObjectType"/>
    <eClassifiers xsi:type="ecore:EClass" name="BoundOperation" eSuperTypes="#//service/Operation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1"
          eType="#//service/MappedTransferObjectType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnboundOperation" eSuperTypes="#//service/Operation #//namespace/NamespaceElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//service/TransferObjectType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="accesspoint" nsURI="http://blackbelt.hu/judo/meta/psm/accesspoint"
      nsPrefix="accesspoint">
    <eClassifiers xsi:type="ecore:EClass" name="ExposedService" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="#//service/UnboundOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessPoint" eSuperTypes="#//namespace/NamespaceElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exposedServices" upperBound="-1"
          eType="#//accesspoint/ExposedService" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exposedGraphs" upperBound="-1"
          eType="#//accesspoint/ExposedGraph" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExposedGraph" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selector" lowerBound="1"
          eType="#//derived/StaticNavigation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entryTransferObject"
          lowerBound="1" eType="#//service/MappedTransferObjectType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="view" nsURI="http://blackbelt.hu/judo/meta/psm/view" nsPrefix="view">
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//view/Component" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="layout" lowerBound="1"
          eType="#//view/LayoutType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" lowerBound="1"
          eType="#//view/AlignmentType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//namespace/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentView" lowerBound="1"
          eType="#//view/ObjectView" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Widget" eSuperTypes="#//view/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferAttribute" lowerBound="1"
          eType="#//service/TransferAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="emittedEvents" upperBound="-1"
          eType="#//view/Event" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectView" eSuperTypes="#//view/Container #//namespace/NamespaceElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferObject" lowerBound="1"
          eType="#//service/TransferObjectType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewType" lowerBound="1"
          eType="#//view/ViewType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
          eType="#//view/Control" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Groupbox" eSuperTypes="#//view/Container #//view/Component"/>
    <eClassifiers xsi:type="ecore:EClass" name="Placeholder" eSuperTypes="#//view/Component">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="popup" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Navigation" abstract="true" eSuperTypes="#//view/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="navigationView" lowerBound="1"
          eType="#//view/ObjectView"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rangeView" eType="#//view/ObjectView"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transferRelation" lowerBound="1"
          eType="#//service/TransferRelation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//view/Navigation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//view/Placeholder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Embedded" eSuperTypes="#//view/Navigation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//view/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//view/Placeholder"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="#//service/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultView" eType="#//view/ObjectView"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="faultViews" upperBound="-1"
          eType="#//view/ObjectView"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="controller" lowerBound="1"
          eType="#//service/TransferAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//view/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VisibleControl" eSuperTypes="#//view/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnabledControl" eSuperTypes="#//view/Control"/>
    <eClassifiers xsi:type="ecore:EEnum" name="EventType">
      <eLiterals name="SYSTEM_CHANGED"/>
      <eLiterals name="USER_CHANGED" value="1"/>
      <eLiterals name="ENABLED" value="2"/>
      <eLiterals name="DISABLED" value="3"/>
      <eLiterals name="SHOWN" value="4"/>
      <eLiterals name="HIDE" value="5"/>
      <eLiterals name="LOADED" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ViewType">
      <eLiterals name="LIST"/>
      <eLiterals name="GRID" value="1"/>
      <eLiterals name="TILE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LayoutType">
      <eLiterals name="HORIZONTAL"/>
      <eLiterals name="VERTICAL" value="1"/>
      <eLiterals name="TAB" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewControl" abstract="true" eSuperTypes="#//view/Component"/>
    <eClassifiers xsi:type="ecore:EClass" name="Event">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" lowerBound="1"
          eType="#//view/EventType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="triggered" lowerBound="1"
          eType="#//view/Action"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MenuComponent" abstract="true" eSuperTypes="#//view/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subMenus" upperBound="-1"
          eType="#//view/Menu" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="menuItems" upperBound="-1"
          eType="#//view/MenuItem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MenuBar" eSuperTypes="#//view/MenuComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Menu" eSuperTypes="#//view/MenuComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="MenuItem" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="view" lowerBound="1"
          eType="#//view/ObjectView"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//view/Placeholder"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntryMenuItem" eSuperTypes="#//view/MenuItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="selector" lowerBound="1"
          eType="#//derived/StaticNavigation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionMenuItem" eSuperTypes="#//view/MenuItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exposedService" lowerBound="1"
          eType="#//service/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserInterface" eSuperTypes="#//namespace/NamespaceElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mainView" lowerBound="1"
          eType="#//view/ObjectView"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selector" eType="#//derived/StaticNavigation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Renderer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Back" eSuperTypes="#//view/ViewControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnboundActionLink" eSuperTypes="#//view/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionView" lowerBound="1"
          eType="#//view/ObjectView"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AlignmentType">
      <eLiterals name="TOP"/>
      <eLiterals name="BOTTOM" value="1"/>
      <eLiterals name="LEFT" value="2"/>
      <eLiterals name="RIGHT" value="3"/>
      <eLiterals name="CENTER" value="4"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="authentication" nsURI="http://blackbelt.hu/judo/meta/psm/authentication"
      nsPrefix="authentication">
    <eClassifiers xsi:type="ecore:EClass" name="PasswordAuthenticatedUser" eSuperTypes="#//authentication/AuthenticatedUser">
      <eStructuralFeatures xsi:type="ecore:EReference" name="password" lowerBound="1"
          eType="#//data/Attribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="login" lowerBound="1"
          eType="#//data/Attribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AuthenticatedUser" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1"
          eType="#//data/EntityType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="authorization" nsURI="http://blackbelt.hu/judo/meta/psm/authorization"
      nsPrefix="authorization">
    <eClassifiers xsi:type="ecore:EClass" name="AuthorizationResource" eSuperTypes="#//namespace/NamespaceElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTypedElements"
          upperBound="-1" eType="#//data/ReferenceTypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//service/Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includedAuthorizationResources"
          upperBound="-1" eType="#//authorization/AuthorizationResource"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
