= judo-meta-psm test
 
image::https://github.com/BlackBeltTechnology/judo-meta-psm/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/judo-meta-psm/actions/workflows/build.yml" float="center"]

== Introduction

> PSM is an acronym, which stands for "Platform Specific Model"

This repository contains the PSM meta model.

It acts as an eclipse plugin with features and sites, can be used standalone and in standard OSGi (without eclipse).

In essence this is the JUDO runtime's meta model or an entry point to actual operations-related modules. From a transformation
point of view this model is the first in the chain, followed by https://github.com/BlackBeltTechnology/judo-meta-asm[ASM], https://github.com/BlackBeltTechnology/judo-meta-measure[Measure], etc...

== Context

This project is a building block of the https://github.com/BlackBeltTechnology/judo-community[judo-community] aggregator
project. In order to better understand how this module fits into our ecosystem, please check the corresponding documentation!

== Contributing to the project

Everyone is welcome to contribute to JUDO! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!

== License

This project is licensed under the https://www.eclipse.org/legal/epl-2.0/[Eclipse Public License - v 2.0].
